from enum import Enum


class FeatType(Enum):
    UNDEFINED = -1
    CODE_AUTHOR = 0
    CODE_AUTHBY = 1
    CODE_CONTRB = 2
    CODE_AUTHOR_DIRECTORY = 3
    CODE_AUTHBY_DIRECTORY = 4
    CODE_CONTRB_DIRECTORY = 5
    SURVEY_BASIC = 10
    SURVEY_COMPLETE = 11
    SOCIAL_CHARACTER = 21
    SOCIAL_QUESTION = 22
    SOCIAL_CODE = 23
    GITHUB_USER_REPOS = 30
    GITHUB_USER_FORKS = 31
    GITHUB_USER_GISTS = 32
    GITHUB_USER_COMMITS = 33
    GITHUB_USER_PULL_REQUESTS = 34
    GITHUB_USER_COMMENTS = 35
    GITHUB_USER_PROFILE_IMAGE = 36
    GITHUB_USER_LOCALITY = 37
    GITHUB_FORK = 40
    GITHUB_FORK_FRESH = 41
    GITHUB_STARGAZE = 42
    GITHUB_WATCH = 43
    GITHUB_ISSUES = 44
    GITHUB_PULL_REQUESTS = 45
    GITHUB_PULL_REQUESTS_MERGED = 46
    GITHUB_COMMENTS = 47
    GITHUB_COMMENT_CHARACTERS = 48
    GITHUB_COMMENT_DIRECTORY = 49
    GITHUB_PULL_CONTENTS_COMMITS = 50
    GITHUB_PULL_CONTENTS_ADDITIONS = 51
    GITHUB_PULL_CONTENTS_DELETIONS = 52
    GITHUB_PULL_CONTENTS_CHANGES = 53
    GITHUB_PULL_CONTENTS_CHANGED_FILES = 54
    ASSIDUITY = 60

    def __repr__(self):
        return self.name